### ISSUE TITLE
no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by kostyay** [takumakume/telepolice#4]
Hey 
Running with GKE I get the following error.
A quick google reveals this.

error: No Auth Provider found for name "gcp"

Seems to be a known problem kubernetes/client-go#242 , importing _ k8s.io/client-go/plugin/pkg/client/auth/gcp seems to resolve it.

**Comment by takumakume** [comment]
Thank you for issue!!
fixed: https://github.com/takumakume/telepolice/releases/tag/v0.0.8
